version: '3'

services:
  log_ingestor:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - elasticsearch
    networks:
      - my_network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
    networks:
      - my_network

  ui:
    build:
      context: .
      dockerfile: Dockerfile.ui
    ports:
      - "3000:80"
    depends_on:
      - log_ingestor
    networks:
      - my_network

networks:
  my_network:
